author: Vanadium Authors
description: V23proxy is a proxy service between Mojo and Vanadium applications.
homepage: https://github.com/vanadium/mojo.v23proxy
name: v23proxy
version: 0.0.1
dependencies:
  mojo_sdk: 0.2.21
dev_dependencies:
  dart_style: any
  test: any
environment:
  sdk: '>=1.12.0 <2.0.0'
