author: Vanadium Authors
description: Echo Server is an example Mojo Dart application that uses the v23proxy.
homepage: https://github.com/vanadium/mojo.v23proxy
name: v23proxy_echo_server
version: 0.0.1
dependencies:
  mojo_sdk: 0.2.21
  v23proxy: '>=0.0.1'
environment:
  sdk: '>=1.12.0 <2.0.0'
dependency_overrides:
  v23proxy:
    path: ../..
