author: Vanadium Authors
description: Fortune Server is an example Mojo Dart application that uses the v23proxy.
homepage: https://github.com/vanadium/mojo.v23proxy
name: v23proxy-fortune-server
version: 0.0.1
dependencies:
  mojo: '>=0.3.0 <0.4.0'
  v23proxy: '>=0.0.1'
dev_dependencies:
  dart_style: any
  test: any
environment:
  sdk: '>=1.12.0 <2.0.0'
dependency_overrides:
  mojo:
    path: ../../.mojo_sdk/mojo/src/out/Debug/gen/dart-pkg/mojo
  v23proxy:
    path: ../..
